name: react-test-app
region: fra
static_sites:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: main
      repo: marioresl/do-test-app
      deploy_on_push: true
    name: do-test-app
    source_dir: /
    envs:
      - key: VITE_FUNCTIONS_BASE_URL
        value: https://faas-fra1-afec6ce7.doserverless.co/api/v1/web/fn-4917e19c-d940-4672-917a-3dcb98bfc84c
        scope: BUILD_TIME
